-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: 15-Dez-2018 às 16:30
-- Versão do servidor: 5.7.19
-- PHP Version: 7.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mymed`
--
CREATE DATABASE IF NOT EXISTS `mymed` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `mymed`;

-- --------------------------------------------------------

--
-- Estrutura da tabela `medico`
--

DROP TABLE IF EXISTS `medico`;
CREATE TABLE IF NOT EXISTS `medico` (
  `crm` varchar(13) NOT NULL,
  `nome` varchar(45) NOT NULL,
  `Especialidade` varchar(30) NOT NULL,
  `descricao` varchar(700) DEFAULT NULL,
  `sexo` varchar(1) DEFAULT NULL,
  `endereco` varchar(100) DEFAULT NULL,
  `valor_consulta` float DEFAULT NULL,
  `n_parcelas` int(11) DEFAULT NULL,
  `foto` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`crm`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `medico`
--

INSERT INTO `medico` (`crm`, `nome`, `Especialidade`, `descricao`, `sexo`, `endereco`, `valor_consulta`, `n_parcelas`, `foto`) VALUES
('78965444-5/BR', 'Dr.Bruno Guedes', 'Dermatologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Joao Monlevade', 60, 2, 'view\\img\\foto1.png'),
('44663528-4/BR', 'Dr. Rodrigo Sales', 'Ortopedia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Sao Domingos do Prata', 90, 3, 'view\\img\\foto2.png'),
('56784321-9/BR', 'Dra. Maria Beatriz', 'Ortopedia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Joao Monlevade', 80, 2, 'view\\img\\foto.png'),
('10207654-3/BR', 'Dr. Patrick Morais', 'Ortopedia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Itabira', 75, 3, 'view\\img\\foto9.png'),
('75687689-5/BR', 'Dra. Emily Medson', 'Ortopedia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Ipatinga', 100, 4, 'view\\img\\foto4.png'),
('96287098-4/BR', 'Dra. Elis Mara', 'Clinica Geral', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Joao Monlevade', 150, 2, 'view\\img\\foto3.png'),
('22287349-1/BR', 'Dra. Morgana Leigim', 'Clinica Geral', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Ipatinga', 200, 3, 'view\\img\\foto5.png'),
('98209683-2/BR', 'Dr. Marcos Moura', 'Clinica Geral', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Joao Monlevade', 200, 2, 'view\\img\\foto16.png'),
('11280987-8/BR', 'Dr. Emerson Dias', 'Clinica Geral', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Itabira', 250, 4, 'view\\img\\foto14.png'),
('39287600-0/BR', 'Dr. Rodrigo Souza', 'Laboratorio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Sao Domingos do Prata', 20, 1, 'view\\img\\foto23.png'),
('87657622-7/BR', 'Dra. Karina Mendes', 'Laboratorio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Joao Monlevade', 25, 1, 'view\\img\\foto11.png'),
('34547582-8/BR', 'Dra. Joice Martins', 'Laboratorio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Itabira', 30, 1, 'view\\img\\foto17.png'),
('09898753-1/BR', 'Dra. Larissa Lima', 'Laboratorio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Ipatinga', 30, 1, 'view\\img\\foto22.png'),
('56749821-4/BR', 'Dra. Helena Santos', 'Dermatologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Joao Monlevade', 75, 3, 'view\\img\\foto13.png'),
('11524386-2/BR', 'Dr. Mascos de Ros', 'Dermatologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Nova Era', 55, 3, 'view\\img\\foto24.png'),
('09065423-9/BR', 'Dra. Amanda Medeiros', 'Dermatologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Joao Monlevade', 60, 2, 'view\\img\\foto20.png'),
('65433872-0/BR', 'Dra. Maria Gabriela', 'Nutricao', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Nova Era', 50, 2, 'view\\img\\foto12.png'),
('08605431-3/BR', 'Dr. Will Jonny', 'Nutricao', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Sao Goncalo', 60, 2, 'view\\img\\foto6.png'),
('50034332-1/BR', 'Dra. Monica Santos', 'Nutricao', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Belo Horizonte', 70, 3, 'view\\img\\foto19.png'),
('60734030-6/BR', 'Dr. Otavio Pontes', 'Nutricao', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Sao Goncalo', 60, 2, 'view\\img\\foto32.png'),
('63553828-5/BR', 'Dra. Vania Costa', 'Pediatria', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Joao Monlevade', 130, 3, 'view\\img\\foto15.png'),
('91827364-7/BR', 'Dra. Elizabete Montesquiel', 'Pediatria', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Nova Era', 150, 3, 'view\\img\\foto25.png'),
('65738211-3/BR', 'Dr. Morgan Yamato', 'Pediatria', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Belo Horizonte', 150, 3, 'view\\img\\foto18.png'),
('75643277-6/BR', 'Dr. Flavio Fonseca', 'Pediatria', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Itabira', 140, 3, 'view\\img\\foto10.png'),
('11156543-8/BR', 'Dr. Milton Raymer', 'Oftamologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Sao Domingos do Prata', 200, 4, 'view\\img\\foto35.png'),
('15467890-1/BR', 'Dra. Sara Miller', 'Oftamologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Ipatinga', 250, 5, 'view\\img\\foto31.png'),
('95645633-4/BR', 'Dr. Miguel Arantes', 'Oftamologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Belo Horizonte', 230, 4, 'view\\img\\foto37.png'),
('09087654-2/BR', 'Dra. Brita Vox', 'Oftamologia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Rio Piracicaba', 240, 4, 'view\\img\\foto30.png'),
('34598670-7/BR', 'Dr. Olavo Brantes', 'Saude Mental', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Joao Monlevade', 150, 3, 'view\\img\\foto33.png'),
('00005476-6/BR', 'Dr. Bernard Boaventura', 'Saude Mental', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'M', 'Rio Piracicaba', 165, 3, 'view\\img\\foto34.png'),
('12262345-5/BR', 'Dra. Alissa Gluz', 'Saude Mental', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Sao Goncalo', 170, 4, 'view\\img\\foto29.png'),
('98721436-9/BR', 'Dra. Angela Gloss', 'Saude Mental', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis vehicula magna sit amet efficitur. Vestibulum pellentesque erat vehicula gravida consequat. Aliquam ornare dolor quis neque pretium, placerat semper ligula mattis. Pellentesque sit amet egestas purus. Curabitur egestas elit nisl, id dictum sapien aliquam id. Nulla facilisi. Curabitur accumsan libero vitae massa vestibulum lacinia. Nam eu augue vitae nulla porta porttitor vitae ac augue. Donec sed elementum odio. Aliquam vel efficitur magna. Phasellus elit dui, tincidunt ac tellus non, porta molestie turpis. ', 'F', 'Belo Horizonte', 160, 3, 'view\\img\\foto27.png');

-- --------------------------------------------------------

--
-- Estrutura da tabela `usuario`
--

DROP TABLE IF EXISTS `usuario`;
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(45) NOT NULL,
  `senha` varchar(20) NOT NULL,
  `email` varchar(50) DEFAULT NULL,
  `sexo` varchar(1) DEFAULT NULL,
  `avatar` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `usuario`
--

INSERT INTO `usuario` (`idusuario`, `nome`, `senha`, `email`, `sexo`, `avatar`) VALUES
(1, 'Marta Lemos', 'mlemos', 'm_lemos@gmail.com', 'F', '\\br\\com\\imed\\view\\img\\foto39.png'),
(2, 'Claire Baker', 'c_baker', 'baker@hotmail.com', 'F', '/br/com/imed/view/img/foto40.png'),
(3, 'Administrador', 'admin', 'admin@admin', 'M', '/br/com/imed/view/img/avatar_padrao.png'),
(4, 'Noa Benningan', '123', 'noa@gmail.com', NULL, NULL),
(5, 'Iris Borgard', '123', 'iris@hotmail.com', NULL, NULL),
(6, 'Lara Mendes', '123', 'lara@gmail.com', NULL, NULL),
(7, 'Usuario Teste', '123', 'test@test.com.br', NULL, NULL),
(8, 'teste1', '123', 'teste@test.com', NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
